version: "0.1"
services:
  auth:
    build: ./auth
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./auth:/auth

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:latest"

volumes:
  pgdata: