[build]
src = "portfolio"

[phases.setup]
nixPkgs = [
    "python38",
    "python38Packages.flask",
    "python38Packages.gunicorn",
    "python38Packages.hupper"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-5001} app:app -w 1"